// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/v1/commit.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommitService_Commit_FullMethodName = "/api.v1.CommitService/Commit"
)

// CommitServiceClient is the client API for CommitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommitService handles file commit lifecycle
// after all data has been written via DataService.
type CommitServiceClient interface {
	Commit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommitRequest, CommitResponse], error)
}

type commitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommitServiceClient(cc grpc.ClientConnInterface) CommitServiceClient {
	return &commitServiceClient{cc}
}

func (c *commitServiceClient) Commit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommitRequest, CommitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommitService_ServiceDesc.Streams[0], CommitService_Commit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommitRequest, CommitResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommitService_CommitClient = grpc.BidiStreamingClient[CommitRequest, CommitResponse]

// CommitServiceServer is the server API for CommitService service.
// All implementations must embed UnimplementedCommitServiceServer
// for forward compatibility.
//
// CommitService handles file commit lifecycle
// after all data has been written via DataService.
type CommitServiceServer interface {
	Commit(grpc.BidiStreamingServer[CommitRequest, CommitResponse]) error
	mustEmbedUnimplementedCommitServiceServer()
}

// UnimplementedCommitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommitServiceServer struct{}

func (UnimplementedCommitServiceServer) Commit(grpc.BidiStreamingServer[CommitRequest, CommitResponse]) error {
	return status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedCommitServiceServer) mustEmbedUnimplementedCommitServiceServer() {}
func (UnimplementedCommitServiceServer) testEmbeddedByValue()                       {}

// UnsafeCommitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommitServiceServer will
// result in compilation errors.
type UnsafeCommitServiceServer interface {
	mustEmbedUnimplementedCommitServiceServer()
}

func RegisterCommitServiceServer(s grpc.ServiceRegistrar, srv CommitServiceServer) {
	// If the following call panics, it indicates UnimplementedCommitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommitService_ServiceDesc, srv)
}

func _CommitService_Commit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommitServiceServer).Commit(&grpc.GenericServerStream[CommitRequest, CommitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommitService_CommitServer = grpc.BidiStreamingServer[CommitRequest, CommitResponse]

// CommitService_ServiceDesc is the grpc.ServiceDesc for CommitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.CommitService",
	HandlerType: (*CommitServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Commit",
			Handler:       _CommitService_Commit_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/commit.proto",
}
