// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/v1/commit.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommitEntry represents a single file to commit.
type CommitEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target path of the file to commit.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Total size of the file or device in bytes.
	TotalSize     uint64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitEntry) Reset() {
	*x = CommitEntry{}
	mi := &file_api_v1_commit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEntry) ProtoMessage() {}

func (x *CommitEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_commit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEntry.ProtoReflect.Descriptor instead.
func (*CommitEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_commit_proto_rawDescGZIP(), []int{0}
}

func (x *CommitEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommitEntry) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// CommitRequest contains a batch of files to commit.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CommitEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_api_v1_commit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_commit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_commit_proto_rawDescGZIP(), []int{1}
}

func (x *CommitRequest) GetEntries() []*CommitEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// CommitResponse confirms committed file paths.
type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_api_v1_commit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_commit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_commit_proto_rawDescGZIP(), []int{2}
}

func (x *CommitResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_api_v1_commit_proto protoreflect.FileDescriptor

const file_api_v1_commit_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/commit.proto\x12\x06api.v1\"@\n" +
	"\vCommitEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\">\n" +
	"\rCommitRequest\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.api.v1.CommitEntryR\aentries\"&\n" +
	"\x0eCommitResponse\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths2L\n" +
	"\rCommitService\x12;\n" +
	"\x06Commit\x12\x15.api.v1.CommitRequest\x1a\x16.api.v1.CommitResponse(\x010\x01B>Z<github.com/RamenDR/ceph-volsync-plugin/internal/proto/api/v1b\x06proto3"

var (
	file_api_v1_commit_proto_rawDescOnce sync.Once
	file_api_v1_commit_proto_rawDescData []byte
)

func file_api_v1_commit_proto_rawDescGZIP() []byte {
	file_api_v1_commit_proto_rawDescOnce.Do(func() {
		file_api_v1_commit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_commit_proto_rawDesc), len(file_api_v1_commit_proto_rawDesc)))
	})
	return file_api_v1_commit_proto_rawDescData
}

var file_api_v1_commit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_commit_proto_goTypes = []any{
	(*CommitEntry)(nil),    // 0: api.v1.CommitEntry
	(*CommitRequest)(nil),  // 1: api.v1.CommitRequest
	(*CommitResponse)(nil), // 2: api.v1.CommitResponse
}
var file_api_v1_commit_proto_depIdxs = []int32{
	0, // 0: api.v1.CommitRequest.entries:type_name -> api.v1.CommitEntry
	1, // 1: api.v1.CommitService.Commit:input_type -> api.v1.CommitRequest
	2, // 2: api.v1.CommitService.Commit:output_type -> api.v1.CommitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_commit_proto_init() }
func file_api_v1_commit_proto_init() {
	if File_api_v1_commit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_commit_proto_rawDesc), len(file_api_v1_commit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_commit_proto_goTypes,
		DependencyIndexes: file_api_v1_commit_proto_depIdxs,
		MessageInfos:      file_api_v1_commit_proto_msgTypes,
	}.Build()
	File_api_v1_commit_proto = out.File
	file_api_v1_commit_proto_goTypes = nil
	file_api_v1_commit_proto_depIdxs = nil
}
