// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/v1/data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompressionAlgo specifies the compression format used for block data.
type CompressionAlgo int32

const (
	CompressionAlgo_COMPRESSION_NONE CompressionAlgo = 0
	CompressionAlgo_COMPRESSION_LZ4  CompressionAlgo = 1
	CompressionAlgo_COMPRESSION_ZSTD CompressionAlgo = 2
)

// Enum value maps for CompressionAlgo.
var (
	CompressionAlgo_name = map[int32]string{
		0: "COMPRESSION_NONE",
		1: "COMPRESSION_LZ4",
		2: "COMPRESSION_ZSTD",
	}
	CompressionAlgo_value = map[string]int32{
		"COMPRESSION_NONE": 0,
		"COMPRESSION_LZ4":  1,
		"COMPRESSION_ZSTD": 2,
	}
)

func (x CompressionAlgo) Enum() *CompressionAlgo {
	p := new(CompressionAlgo)
	*p = x
	return p
}

func (x CompressionAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_data_proto_enumTypes[0].Descriptor()
}

func (CompressionAlgo) Type() protoreflect.EnumType {
	return &file_api_v1_data_proto_enumTypes[0]
}

func (x CompressionAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionAlgo.Descriptor instead.
func (CompressionAlgo) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{0}
}

// ChangedBlock represents a modified data range.
type ChangedBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Byte offset where the write should begin.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Length of the write in bytes.
	Length uint64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	// Data payload. May be empty if is_zero is true.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Indicates this write represents a zeroed range.
	IsZero bool `protobuf:"varint,4,opt,name=is_zero,json=isZero,proto3" json:"is_zero,omitempty"`
	// Unique ID for deduplication and tracking.
	RequestId uint64 `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Compression algorithm applied to data.
	Compression CompressionAlgo `protobuf:"varint,6,opt,name=compression,proto3,enum=api.v1.CompressionAlgo" json:"compression,omitempty"`
	// Total size of the file or device in bytes.
	TotalSize     uint64 `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedBlock) Reset() {
	*x = ChangedBlock{}
	mi := &file_api_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedBlock) ProtoMessage() {}

func (x *ChangedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedBlock.ProtoReflect.Descriptor instead.
func (*ChangedBlock) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *ChangedBlock) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChangedBlock) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ChangedBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChangedBlock) GetIsZero() bool {
	if x != nil {
		return x.IsZero
	}
	return false
}

func (x *ChangedBlock) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChangedBlock) GetCompression() CompressionAlgo {
	if x != nil {
		return x.Compression
	}
	return CompressionAlgo_COMPRESSION_NONE
}

func (x *ChangedBlock) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// SyncRequest wraps a write operation sent over the stream.
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Operation:
	//
	//	*SyncRequest_Write
	Operation     isSyncRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRequest) GetOperation() isSyncRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *SyncRequest) GetWrite() *WriteRequest {
	if x != nil {
		if x, ok := x.Operation.(*SyncRequest_Write); ok {
			return x.Write
		}
	}
	return nil
}

type isSyncRequest_Operation interface {
	isSyncRequest_Operation()
}

type SyncRequest_Write struct {
	Write *WriteRequest `protobuf:"bytes,1,opt,name=write,proto3,oneof"`
}

func (*SyncRequest_Write) isSyncRequest_Operation() {}

// WriteRequest represents a batched write operation.
type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target path or object identifier.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// List of changed blocks to be written.
	Blocks        []*ChangedBlock `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_api_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteRequest) GetBlocks() []*ChangedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// DeleteRequest represents a batch file or directory deletion operation.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target paths to files or directories to delete (recursive by default).
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// SyncResponse carries acknowledged request IDs
// for window release on the source side.
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request IDs that the destination has processed.
	AcknowledgedIds []uint64 `protobuf:"varint,1,rep,packed,name=acknowledged_ids,json=acknowledgedIds,proto3" json:"acknowledged_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *SyncResponse) GetAcknowledgedIds() []uint64 {
	if x != nil {
		return x.AcknowledgedIds
	}
	return nil
}

// DeleteResponse is empty on success.
// Errors are reported via gRPC status codes.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{5}
}

var File_api_v1_data_proto protoreflect.FileDescriptor

const file_api_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/data.proto\x12\x06api.v1\"\xe4\x01\n" +
	"\fChangedBlock\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x17\n" +
	"\ais_zero\x18\x04 \x01(\bR\x06isZero\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x04R\trequestId\x129\n" +
	"\vcompression\x18\x06 \x01(\x0e2\x17.api.v1.CompressionAlgoR\vcompression\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x04R\ttotalSize\"N\n" +
	"\vSyncRequest\x12,\n" +
	"\x05write\x18\x01 \x01(\v2\x14.api.v1.WriteRequestH\x00R\x05writeB\v\n" +
	"\toperationJ\x04\b\x03\x10\x04\"P\n" +
	"\fWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12,\n" +
	"\x06blocks\x18\x02 \x03(\v2\x14.api.v1.ChangedBlockR\x06blocks\"%\n" +
	"\rDeleteRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"9\n" +
	"\fSyncResponse\x12)\n" +
	"\x10acknowledged_ids\x18\x01 \x03(\x04R\x0facknowledgedIds\"\x10\n" +
	"\x0eDeleteResponse*R\n" +
	"\x0fCompressionAlgo\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x00\x12\x13\n" +
	"\x0fCOMPRESSION_LZ4\x10\x01\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x022}\n" +
	"\vDataService\x125\n" +
	"\x04Sync\x12\x13.api.v1.SyncRequest\x1a\x14.api.v1.SyncResponse(\x010\x01\x127\n" +
	"\x06Delete\x12\x15.api.v1.DeleteRequest\x1a\x16.api.v1.DeleteResponseB>Z<github.com/RamenDR/ceph-volsync-plugin/internal/proto/api/v1b\x06proto3"

var (
	file_api_v1_data_proto_rawDescOnce sync.Once
	file_api_v1_data_proto_rawDescData []byte
)

func file_api_v1_data_proto_rawDescGZIP() []byte {
	file_api_v1_data_proto_rawDescOnce.Do(func() {
		file_api_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_data_proto_rawDesc), len(file_api_v1_data_proto_rawDesc)))
	})
	return file_api_v1_data_proto_rawDescData
}

var file_api_v1_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_data_proto_goTypes = []any{
	(CompressionAlgo)(0),   // 0: api.v1.CompressionAlgo
	(*ChangedBlock)(nil),   // 1: api.v1.ChangedBlock
	(*SyncRequest)(nil),    // 2: api.v1.SyncRequest
	(*WriteRequest)(nil),   // 3: api.v1.WriteRequest
	(*DeleteRequest)(nil),  // 4: api.v1.DeleteRequest
	(*SyncResponse)(nil),   // 5: api.v1.SyncResponse
	(*DeleteResponse)(nil), // 6: api.v1.DeleteResponse
}
var file_api_v1_data_proto_depIdxs = []int32{
	0, // 0: api.v1.ChangedBlock.compression:type_name -> api.v1.CompressionAlgo
	3, // 1: api.v1.SyncRequest.write:type_name -> api.v1.WriteRequest
	1, // 2: api.v1.WriteRequest.blocks:type_name -> api.v1.ChangedBlock
	2, // 3: api.v1.DataService.Sync:input_type -> api.v1.SyncRequest
	4, // 4: api.v1.DataService.Delete:input_type -> api.v1.DeleteRequest
	5, // 5: api.v1.DataService.Sync:output_type -> api.v1.SyncResponse
	6, // 6: api.v1.DataService.Delete:output_type -> api.v1.DeleteResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_data_proto_init() }
func file_api_v1_data_proto_init() {
	if File_api_v1_data_proto != nil {
		return
	}
	file_api_v1_data_proto_msgTypes[1].OneofWrappers = []any{
		(*SyncRequest_Write)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_data_proto_rawDesc), len(file_api_v1_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_data_proto_goTypes,
		DependencyIndexes: file_api_v1_data_proto_depIdxs,
		EnumInfos:         file_api_v1_data_proto_enumTypes,
		MessageInfos:      file_api_v1_data_proto_msgTypes,
	}.Build()
	File_api_v1_data_proto = out.File
	file_api_v1_data_proto_goTypes = nil
	file_api_v1_data_proto_depIdxs = nil
}
