// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/v1/hash.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HashService_CompareHashes_FullMethodName = "/api.v1.HashService/CompareHashes"
)

// HashServiceClient is the client API for HashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HashService allows the source to check which chunks the destination
// already has, avoiding redundant data transfer.
type HashServiceClient interface {
	CompareHashes(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HashBatchRequest, HashBatchResponse], error)
}

type hashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHashServiceClient(cc grpc.ClientConnInterface) HashServiceClient {
	return &hashServiceClient{cc}
}

func (c *hashServiceClient) CompareHashes(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HashBatchRequest, HashBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HashService_ServiceDesc.Streams[0], HashService_CompareHashes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HashBatchRequest, HashBatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HashService_CompareHashesClient = grpc.BidiStreamingClient[HashBatchRequest, HashBatchResponse]

// HashServiceServer is the server API for HashService service.
// All implementations must embed UnimplementedHashServiceServer
// for forward compatibility.
//
// HashService allows the source to check which chunks the destination
// already has, avoiding redundant data transfer.
type HashServiceServer interface {
	CompareHashes(grpc.BidiStreamingServer[HashBatchRequest, HashBatchResponse]) error
	mustEmbedUnimplementedHashServiceServer()
}

// UnimplementedHashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHashServiceServer struct{}

func (UnimplementedHashServiceServer) CompareHashes(grpc.BidiStreamingServer[HashBatchRequest, HashBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method CompareHashes not implemented")
}
func (UnimplementedHashServiceServer) mustEmbedUnimplementedHashServiceServer() {}
func (UnimplementedHashServiceServer) testEmbeddedByValue()                     {}

// UnsafeHashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashServiceServer will
// result in compilation errors.
type UnsafeHashServiceServer interface {
	mustEmbedUnimplementedHashServiceServer()
}

func RegisterHashServiceServer(s grpc.ServiceRegistrar, srv HashServiceServer) {
	// If the following call panics, it indicates UnimplementedHashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HashService_ServiceDesc, srv)
}

func _HashService_CompareHashes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HashServiceServer).CompareHashes(&grpc.GenericServerStream[HashBatchRequest, HashBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HashService_CompareHashesServer = grpc.BidiStreamingServer[HashBatchRequest, HashBatchResponse]

// HashService_ServiceDesc is the grpc.ServiceDesc for HashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.HashService",
	HandlerType: (*HashServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompareHashes",
			Handler:       _HashService_CompareHashes_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/hash.proto",
}
