apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: cft-dest
spec:  
  # trigger: 
  #   manual: "hash-1"
  # every 5 minutes 
    # schedule: "*/5 * * * *"
  external: 
    provider: "openshift-storage.cephfs.csi.ceph.com" # driver name
    parameters:
      # secretKey: volsync-cephfs-dest
      # serviceType: <ClusterIP(default) | LoadBalancer>
      
      destinationPVC: cft-dest-pvc
      
      # storageClassName: ocs-storagecluster-cephfs
      # volumeSnapshotClassName: ocs-storagecluster-cephfsplugin-snapclass

      storageClassName: rook-cephfs
      volumeSnapshotClassName: csi-cephfsplugin-snapclass
      
      copyMethod: Snapshot

      # copyMethod: Direct
      # baseSnapshotName: <base-snapshot-name> # required for Diff sync
      # targetSnapshotName: <target-snapshot-name> # required for Diff sync
      # parentVolumeName: <parent-volume-name> # required for Diff sync 
---
# apiVersion: v1
# data:
#   psk.txt: dm9sc3luYzo2NzI5MDQ3OTJmZjg3YTA1YzA5MGIwZjc0NDNjYzBkODE0ZTRiNTg0NmIyOTVmZGQzYmRhOWQxYWYxZDUxNWE4YmI5OWMwMDA2NDE0MzM3MDU1OTczYmU1NTVhOTc5NzkxMWZkYTZlMTQyMzYzYmVhOGRlMTk0NzhjM2JmOWM5NQ==
# kind: Secret
# metadata:
#   name: volsync-cephfs-dest
#   namespace: ceph-volsync-plugin-operator-system
# type: Opaque
# ---
# apiVersion: multicluster.x-k8s.io/v1alpha1
# kind: ServiceExport
# metadata:
#   name: volsync-cephfs-dst-dest
#   namespace: ceph-volsync-plugin-operator-system
