apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: dest
spec:  
  # trigger: 
  #   manual: "hash-1"
  # every 5 minutes 
    # schedule: "*/5 * * * *"
  external: 
    provider: "openshift-storage.cephfs.csi.ceph.com" # driver name
    parameters:
      # keySecret: <secretName>
      # serviceType: <ClusterIP(default) | LoadBalancer>
      
      destinationPVC: dest-pvc
      
      storageClassName: rook-cephfs
      volumeSnapshotClassName: csi-cephfsplugin-snapclass 
      
      copyMethod: Snapshot

      # copyMethod: Direct
      # baseSnapshotName: <base-snapshot-name> # required for Diff sync
      # targetSnapshotName: <target-snapshot-name> # required for Diff sync
      # parentVolumeName: <parent-volume-name> # required for Diff sync 