apiVersion: v1
data:
  psk.txt: dm9sc3luYzo2NzI5MDQ3OTJmZjg3YTA1YzA5MGIwZjc0NDNjYzBkODE0ZTRiNTg0NmIyOTVmZGQzYmRhOWQxYWYxZDUxNWE4YmI5OWMwMDA2NDE0MzM3MDU1OTczYmU1NTVhOTc5NzkxMWZkYTZlMTQyMzYzYmVhOGRlMTk0NzhjM2JmOWM5NQ==
kind: Secret
metadata:
  name: volsync-cephfs-dest
  namespace: ceph-volsync-plugin-operator-system
type: Opaque
