apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: src
spec:    
  sourcePVC: src-pvc
  trigger: 
    manual: "hash-4" 
    # every 5 minutes
    # schedule: "*/3 * * * *"
  external:
    provider: "openshift-storage.cephfs.csi.ceph.com" # driver name
    parameters:
      secretKey: volsync-cephfs-dest
      address: volsync-cephfs-dst-dest
      # port: 
      # serviceType: <ClusterIP(default) | LoadBalancer>
      
      # destinationPVC: dest-pvc
      
      storageClassName: rook-cephfs
      volumeSnapshotClassName: csi-cephfsplugin-snapclass 
      
      copyMethod: Direct
      baseSnapshotName: snap-2 # required for Diff sync
      targetSnapshotName: snap-3 # required for Diff sync
      volumeName: pvc-dc07406a-028b-4d4f-863c-0dd6f7a5ec23  # required for Diff sync