// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/data.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangedBlock represents a modified data range.
type ChangedBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Byte offset where the write should begin.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Length of the write in bytes.
	Length uint64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	// Data payload. May be empty if is_zero is true.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Indicates this write represents a zeroed range.
	IsZero        bool `protobuf:"varint,4,opt,name=is_zero,json=isZero,proto3" json:"is_zero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedBlock) Reset() {
	*x = ChangedBlock{}
	mi := &file_api_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedBlock) ProtoMessage() {}

func (x *ChangedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedBlock.ProtoReflect.Descriptor instead.
func (*ChangedBlock) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *ChangedBlock) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChangedBlock) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ChangedBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChangedBlock) GetIsZero() bool {
	if x != nil {
		return x.IsZero
	}
	return false
}

// WriteRequest represents a batched write operation.
type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target path or object identifier.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// List of changed blocks to be written.
	Blocks        []*ChangedBlock `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_api_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteRequest) GetBlocks() []*ChangedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// WriteResponse is empty on success.
// Errors are reported via gRPC status codes.
type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_api_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_data_proto_rawDescGZIP(), []int{2}
}

var File_api_v1_data_proto protoreflect.FileDescriptor

const file_api_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/data.proto\x12\x06api.v1\"k\n" +
	"\fChangedBlock\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x17\n" +
	"\ais_zero\x18\x04 \x01(\bR\x06isZero\"P\n" +
	"\fWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12,\n" +
	"\x06blocks\x18\x02 \x03(\v2\x14.api.v1.ChangedBlockR\x06blocks\"\x0f\n" +
	"\rWriteResponse2C\n" +
	"\vDataService\x124\n" +
	"\x05Write\x12\x14.api.v1.WriteRequest\x1a\x15.api.v1.WriteResponseB\x85\x01\n" +
	"\n" +
	"com.api.v1B\tDataProtoP\x01Z3github.com/RamenDR/ceph-volsync-plugin/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_data_proto_rawDescOnce sync.Once
	file_api_v1_data_proto_rawDescData []byte
)

func file_api_v1_data_proto_rawDescGZIP() []byte {
	file_api_v1_data_proto_rawDescOnce.Do(func() {
		file_api_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_data_proto_rawDesc), len(file_api_v1_data_proto_rawDesc)))
	})
	return file_api_v1_data_proto_rawDescData
}

var file_api_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_data_proto_goTypes = []any{
	(*ChangedBlock)(nil),  // 0: api.v1.ChangedBlock
	(*WriteRequest)(nil),  // 1: api.v1.WriteRequest
	(*WriteResponse)(nil), // 2: api.v1.WriteResponse
}
var file_api_v1_data_proto_depIdxs = []int32{
	0, // 0: api.v1.WriteRequest.blocks:type_name -> api.v1.ChangedBlock
	1, // 1: api.v1.DataService.Write:input_type -> api.v1.WriteRequest
	2, // 2: api.v1.DataService.Write:output_type -> api.v1.WriteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_data_proto_init() }
func file_api_v1_data_proto_init() {
	if File_api_v1_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_data_proto_rawDesc), len(file_api_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_data_proto_goTypes,
		DependencyIndexes: file_api_v1_data_proto_depIdxs,
		MessageInfos:      file_api_v1_data_proto_msgTypes,
	}.Build()
	File_api_v1_data_proto = out.File
	file_api_v1_data_proto_goTypes = nil
	file_api_v1_data_proto_depIdxs = nil
}
