// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mover/version/v1/done.proto

package versionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Explicit empty request for forward compatibility.
type DoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneRequest) Reset() {
	*x = DoneRequest{}
	mi := &file_mover_version_v1_done_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneRequest) ProtoMessage() {}

func (x *DoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mover_version_v1_done_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneRequest.ProtoReflect.Descriptor instead.
func (*DoneRequest) Descriptor() ([]byte, []int) {
	return file_mover_version_v1_done_proto_rawDescGZIP(), []int{0}
}

// DoneResponse is empty on success.
// Errors are reported via gRPC status codes.
type DoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneResponse) Reset() {
	*x = DoneResponse{}
	mi := &file_mover_version_v1_done_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneResponse) ProtoMessage() {}

func (x *DoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mover_version_v1_done_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneResponse.ProtoReflect.Descriptor instead.
func (*DoneResponse) Descriptor() ([]byte, []int) {
	return file_mover_version_v1_done_proto_rawDescGZIP(), []int{1}
}

var File_mover_version_v1_done_proto protoreflect.FileDescriptor

const file_mover_version_v1_done_proto_rawDesc = "" +
	"\n" +
	"\x1bmover/version/v1/done.proto\x12\x10mover.version.v1\"\r\n" +
	"\vDoneRequest\"\x0e\n" +
	"\fDoneResponse2T\n" +
	"\vDoneService\x12E\n" +
	"\x04Done\x12\x1d.mover.version.v1.DoneRequest\x1a\x1e.mover.version.v1.DoneResponseB\xc6\x01\n" +
	"\x14com.mover.version.v1B\tDoneProtoP\x01ZAgithub.com/RamenDR/ceph-volsync-plugin/mover/version/v1;versionv1\xa2\x02\x03MVX\xaa\x02\x10Mover.Version.V1\xca\x02\x10Mover\\Version\\V1\xe2\x02\x1cMover\\Version\\V1\\GPBMetadata\xea\x02\x12Mover::Version::V1b\x06proto3"

var (
	file_mover_version_v1_done_proto_rawDescOnce sync.Once
	file_mover_version_v1_done_proto_rawDescData []byte
)

func file_mover_version_v1_done_proto_rawDescGZIP() []byte {
	file_mover_version_v1_done_proto_rawDescOnce.Do(func() {
		file_mover_version_v1_done_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mover_version_v1_done_proto_rawDesc), len(file_mover_version_v1_done_proto_rawDesc)))
	})
	return file_mover_version_v1_done_proto_rawDescData
}

var file_mover_version_v1_done_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mover_version_v1_done_proto_goTypes = []any{
	(*DoneRequest)(nil),  // 0: mover.version.v1.DoneRequest
	(*DoneResponse)(nil), // 1: mover.version.v1.DoneResponse
}
var file_mover_version_v1_done_proto_depIdxs = []int32{
	0, // 0: mover.version.v1.DoneService.Done:input_type -> mover.version.v1.DoneRequest
	1, // 1: mover.version.v1.DoneService.Done:output_type -> mover.version.v1.DoneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mover_version_v1_done_proto_init() }
func file_mover_version_v1_done_proto_init() {
	if File_mover_version_v1_done_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mover_version_v1_done_proto_rawDesc), len(file_mover_version_v1_done_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mover_version_v1_done_proto_goTypes,
		DependencyIndexes: file_mover_version_v1_done_proto_depIdxs,
		MessageInfos:      file_mover_version_v1_done_proto_msgTypes,
	}.Build()
	File_mover_version_v1_done_proto = out.File
	file_mover_version_v1_done_proto_goTypes = nil
	file_mover_version_v1_done_proto_depIdxs = nil
}
